# k8s/mongo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  # Use more secure credentials for a real production environment
  mongo-root-username: "admin"
  mongo-root-password: "password123"